# Generated by Django 5.1.2 on 2024-10-23 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='address_company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=20)),
                ('street', models.CharField(max_length=20)),
                ('number', models.IntegerField()),
                ('opening_hours', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='connection_info_company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_phone', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=10)),
                ('vk', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='info_company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slogan', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='reviews_company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('estimation', models.IntegerField()),
                ('reviews_text', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='services_company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_string', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('show', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='techniques_company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('number_phone', models.CharField(max_length=10)),
                ('FCS', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=20)),
                ('ID_string', models.CharField(max_length=50)),
                ('status', models.BooleanField()),
            ],
        ),
    ]
